version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    env_file: 
      - .env  # Load environment variables 
    depends_on:
      - db  # Ensure the database container is ready before starting Flask
    volumes:
      - .:/app  # Mount local project directory to the container for development
  
  db:
    image: postgres:16.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pllkcooray
      POSTGRES_DB: inventoryDB
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist PostgreSQL data

volumes:
  db_data: 
